export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_ALL_PROFILES = 'GET_ALL_PROFILES';
export const PROFILE_ERROR = 'PROFILE_ERROR';

export const GET_BANK = 'GET_BANK';
export const BANK_ERROR = 'BANK_ERROR';

export const GET_ALL_TRANSACTIONS = 'GET_ALL_TRANSACTIONS';
export const MAKE_TRANSACTION = 'MAKE_TRANSACTION';
export const MAKE_TRANSACTION_ERROR = 'MAKE_TRANSACTION_ERROR';
export const TRANSACTION_ERROR = 'TRANSACTION_ERROR';

export const CREDIT = 'CREDIT';
export const CREDIT_ERROR = 'CREDIT_ERROR';
export const DEBIT = 'DEBIT';
export const DEBIT_ERROR = 'DEBIT_ERROR';
